# Generated by Django 5.2 on 2025-05-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_patientprofile_assigned_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='assigned_doc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
