# Generated by Django 5.2 on 2025-05-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patientprofile_assigned_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='assigned_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctorprofile'),
        ),
    ]
