# Generated by Django 5.2 on 2025-05-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_patientprofile_assigned_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='patient_id',
        ),
    ]
