# Generated by Django 5.2 on 2025-05-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_patientprofile_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
