# Generated by Django 5.2 on 2025-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_patientprofile_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='dieases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='symptomps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
