# Generated by Django 5.2 on 2025-05-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdoctor', '0001_initial'),
        ('userpatient', '0003_delete_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
