# Generated by Django 5.2 on 2025-05-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpatient', '0002_patient_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
