# Generated by Django 5.2 on 2025-05-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usernurse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nurse',
        ),
    ]
